apiVersion: apps/v1
kind: Deployment
metadata:
  name: blinkhash-pool
spec:
  selector:
    matchLabels:
      run: blinkhash
  replicas: 2
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        run: blinkhash
    spec:
      containers:
      - name: blinkhash-server
        image: blinkhash-pool
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: blinkhash-api
  labels:
    run: blinkhash
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
    protocol: TCP
  selector:
    run: blinkhash
---
apiVersion: v1
kind: Service
metadata:
  name: blinkhash-pool
  labels:
    run: blinkhash
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30002
    protocol: TCP
  selector:
    run: blinkhash
